# Generated by Django 4.2.4 on 2024-05-12 19:12

from django.db import migrations


def set_age_group(apps, schema_editor):
    person = apps.get_model('main_app', 'Person')
    all_persons = person.objects.all()

    for p in all_persons:
        if p.age <= 12:
            p.age_group = 'Child'
        elif p.age in range(13, 18):
            p.age_group = 'Teen'
        else:
            p.age_group = 'Adult'
        p.save()

def reverse_set_age_group(apps, schema_editor):
    person = apps.get_model("main_app", "Person")
    all_persons = person.objects.all()
    for p in all_persons:
        p.group = "No age group"
        p.save()
        

class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_person'),
    ]

    operations = [
        migrations.RunPython(set_age_group, reverse_code=reverse_set_age_group)
    ]