# Generated by Django 4.2.4 on 2024-05-12 19:27

from django.db import migrations


def set_price_group(apps, schema_editor):
    item_model = apps.get_model('main_app', 'Item')
    all_items = item_model.objects.all()

    for i in all_items:
        if i.price <= 10:
            i.rarity = 'Rare'
        elif i.price in range(11, 21):
            i.rarity = 'Very Rare'
        elif i.price in range(20, 31):
            i.rarity = 'Extremely Rare'
        else:
            i.rarity = 'Mega Rare'
        i.save

def reverse_set_price_group(apps, schema_editor):
    item_model = apps.get_model('main_app', 'Item')
    all_items = item_model.objects.all()
    for i in all_items:
        i.rarity = 'empty'
        i.save()

class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_item'),
    ]

    operations = [
        migrations.RunPython(set_price_group, reverse_code=reverse_set_price_group)
    ]