# Generated by Django 4.2.4 on 2024-05-12 19:59

from django.db import migrations

def set_smart_phone_price(apps, schema_editor):
    smart_phone_model = apps.get_model('main_app', 'Smartphone')
    all_smartphones = smart_phone_model.objects.all()

    for s in all_smartphones:
        s.price = 120 * len(s)
        s.save()

def reset_smart_phone_price(apps, schema_editor):
    smart_phone_model = apps.get_model('main_app', 'Smartphone')
    all_smartphones = smart_phone_model.objects.all()

    for s in all_smartphones:
        s.price = 0
        s.save()

def set_category_smart_phones(apps, schema_editor):
    smart_phone_model = apps.get_model("main_app", "Smartphone")
    all_smartphones = smart_phone_model.objects.all()

    for s in all_smartphones:
        if s.price < 750:
            s.category = "Cheap"
        else:
            s.category = "Expensive"
        s.save()


def reset_category_smart_phones(apps, schema_editor):
    smart_phone_model = apps.get_model("main_app", "Smartphone")
    all_smartphones = smart_phone_model.objects.all()

    for s in all_smartphones:
        s.category = "empty"
        s.save()

class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_smartphone'),
    ]

    operations = [
        migrations.RunPython(set_smart_phone_price, reverse_code=reset_smart_phone_price),
        migrations.RunPython(set_category_smart_phones, reverse_code=reset_category_smart_phones)
    ]
