# Generated by Django 4.2.4 on 2024-05-04 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_exercise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
